name: Publish package to the Maven Central Repository
on:
  push:
    branches: [publish]
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Decode and Import GPG key
        run: |
          echo -n "${{ secrets.MAVEN_GPG_PRIVATE_KEY }}" > encoded-key
          cat encoded-key | tr -d '\n' > encoded-key-no-newlines
          base64 --decode encoded-key-no-newlines > private-key.gpg
          gpg --batch --yes --import private-key.gpg
          gpg --list-secret-keys --keyid-format LONG
      - name: Create settings.xml with server-id:"ossrh"
        run: |
          echo "<settings><servers><server><id>ossrh</id><username>${{ secrets.OSSRH_USERNAME }}</username><password>${{ secrets.OSSRH_TOKEN }}</password></server></servers></settings>" > /home/runner/.m2/settings.xml
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}